#!/bin/bash

sudo apt update
sudo apt install default-jdk

wget http://www-us.apache.org/dist/kafka/2.7.0/kafka_2.13-2.7.0.tgz -O /usr/local/kafka.tgz
tar xzf kafka.tgz

wget http://www-us.apache.org/dist/kafka/2.7.0/kafka_2.13-2.7.0.tgz -O /usr/local/kafka.tgz
